server:
  port: 9000

spring:
  application:
    name: ad-gateway
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

zuul:
  prefix: /api
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: eureka-client-ad-sponsor
      strip-prefix: false
    search:
      path: /ad-search/**
      serviceId: eureka-client-ad-search
      strip-prefix: false
      #127.0.0.1:9000/api/ad-search/fetchAds
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
